### ISSUE TITLE
`make` command to populate db witih dummy data

### ISSUE THREAD

**Issue by tgrigoruk** [Geek-Collectors-Network/geek-collectors-network#107]
We need to to be able to easily create a database (e.g. on `make dev`) that's populated with dummy data we can use for testing.

In order to properly test auth, profile, and friending features we need dummy data for:

- [ ] `user` - a dozen users, some with missing fields
- [ ] `tag` - a ton of tags, maybe use a script to pull a few hundo from the net
- [ ] `userInterestTag` - some users have lots, some have few, various degrees of overlap
- [ ] `friendship` - should reflect different degrees of separation

Create scripts to:
- [x] create db and populate on project build
- [x]  simplify 'refreshing' db if schema changes (drop tables, delete migrations, etc.)

Perhaps use factories to create above entities, e.g. using [Faker](https://fakerjs.dev/guide/)

**Comment by FoRVaiS** [comment]
We need an approach where we can write to the database _after_ the tables have been created as well as validating that our dummy data matches the structure of our tables -- for when our models inevitably change.

***NOTE**: I think we should merge all of our models `models/schema.ts`, I don't think they need to be separated. This can be done in the same PR.

### Data Population
We create a file `models/dummy.ts` that contains a function specifically to write dummy data:
```typescript
writeDummyToDb(db: ReturnType<typeof drizzle>);
```

The `dummy.ts` will import the schemas and insert data using drizzle. The data may use static/pre-defined or generated.

### Reset Database
`make dev` will delete the MySQL container and create a new MySQL Database but unfortunately, the MySQL image makes this method extra painful because the start-up time takes anywhere from ~10s to ~20s.

There are two options:
#### Script
1. Create a bash script to drop all tables from the database
    - Callable using `make reset-db`
2. Reload the API to re-create the tables

#### Lazy Loading
1. Run `make dev`
2. Connect to the DB asynchronously -- resources.db will be NULL until successfully connected
    - The API will immediately be ready for connection
    - Database operations will be queued until the connection is ready, requests shall hang

### Delete Migrations
Generally, we should avoid deleting migrations unless we have SQL errors blocking the API from starting:
1. Changing the datatypes of a column from varchar -> int
    - Not supported, can not convert characters into integers
2. Using FKs in a way we're not supposed to
3. Other ways to violate SQL schemas we don't know about

**Comment by FoRVaiS** [comment]
Using a connection pool doesn't work because it does not attempt to try a failed connection. Once it receives a "Connection Refused" response, it trigger an exception right away.

We will have to write a script to manually clean the database.

**Comment by tgrigoruk** [comment]
The`reset-db` process works great!
And I do like having all models merged into `schema.ts`

I can fill out `dummy.ts` with some more "realistic" data. It might be good for all of us to go over the models again just to confirm our schema.
